name: "install nbplanetary"
description: "Install nbplanetary and dependencies via pip"
runs:
  using: "composite"
  steps:
    - name: Install GDAL
      run: |
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        pip install GDAL==3.2.3
        pip install jupyter
        pip install -e .
