name: "install nbplanetary"
description: "Install nbplanetary and dependencies via pip"
runs:
  using: "composite"
  steps:
    - name: setup-conda
      # You may pin to the exact commit or the version.
      # uses: s-weigand/setup-conda@12b718b536e4be4da931f6d0fcfcc40a646ffed9
      uses: s-weigand/setup-conda@v1.1.1
      with:
        # Whether to activate the conda base env (Default: 'true')
        activate-conda: # optional, default is true
        # If conda should be updated before running other commands (Default: 'false')
        update-conda: # optional, default is false
        # Python version which should be installed with conda (default: 'Default')
        python-version: "3.10" # optional, default is default
        # Additional channels like 'conda-forge' which can be used to install packages
        conda-channels: "conda-forge" # optional, default is
    - name: Install mamba
      shell: bash
      run: conda install -c conda-forge mamba -y
    - name: Install GDAL
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
          from configparser import ConfigParser
          import subprocess
          config = ConfigParser(delimiters=['='])
          config.read('settings.ini')
          cfg = config['DEFAULT']
          requirements = cfg.get('requirements', '')
          cmd = "mamba install " + requirements + " -y"
          print("Command to run:", cmd)
          ret = subprocess.call(cmd, shell=True)
          print("returned_value:", ret)
    - name: Install package
      shell: bash
      run: pip install -e ".[dev]"
