name: "nbdev prep"
description: "Prepare doc creation with nbdev"
inputs:
  pre:
    description: "Install prerelease nbdev/execnb from master?"
    required: false
    default: ""
  ghtoken:
    description: "GitHub token"
    default: ${{ github.token }}
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        # cache: "pip"

    - name: Install nbdev tools
      env:
        USE_PRE: ${{ inputs.pre }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -Uq git+https://github.com/fastai/ghapi.git # you need this for enabling pages
        if [ $USE_PRE]; then
          pip install -Uq git+https://github.com/fastai/fastcore.git
          pip install -Uq git+https://github.com/fastai/execnb.git
          pip install -Uq git+https://github.com/fastai/nbdev.git
          echo "installed pre-released nbdev tools"
        else
          pip install -Uq nbdev
          echo "installed latest nbdev release"
        fi
