on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo build-id to target
        run: echo ${{ inputs.build_id }}
